[package]
name = "miv"
version = "0.1.0"
authors = ["Xavier Perez <duosrx@gmail.com>"]

[dependencies]
rustbox = "*"
termion = "*"

[lib]
name = "miv"
path = "src/miv/lib.rs"

[[bin]]
name = "miv"
doc = false
